/* autogenerated by Processing revision 1295 on 2025-03-06 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class storybookGame extends PApplet {

//initialize variables
PImage castleImg;
PFont font;
public battles battle = new battles();
public int round = 0;
public boolean battleT = false;
public PImage battleBackground;
public PImage cheeseImg;
public PImage kingImg;
public PImage wolfImg;
public PImage ghostImg;
public PImage hotDogImg;
public PImage boqImg;
public PImage gretImg;
public PImage blamImg;
public PImage bartImg;
public boolean kick = false;
public boolean punch = false;
public boolean lose = false;
public boolean win = false;
public boolean leftDoor;
public characters Bart;
public characters Boq;
public characters Gret;
public characters Blam;
public characters Cheese;
public characters Ghost;
public characters King;
public characters Wolf;
public characters HotDog;
public characters turn;
public dialogueBubble dialogue = new dialogueBubble("Is that the castle?", "Boq");
public dialogueBubble system = new dialogueBubble("Wolf");





//all dialogue in order
String[] allDialogue = {
  "Is that the castle?",
  "Yeah Boq, come on. Are you blind?",
  "Stop being so mean to him!",
  "It looks like there’s a gate across the bridge.",
  "Let’s head towards it.",
  "OMG a dog!",
  "Boq runs towards the large wolf blocking the \n path.",
  "BOQ NO COME BACK!",
  "They all chase after him.",
  "Battle begins.",
  "Bart and Boq are huddled together, shaken \n up from the battle.",
  "Gret notices a key that was attached to the \n wolf’s collar.",
  "This must be the key to the gate!",
  "Get up Bart and Boq. You’re such children.",
  "We need to keep moving.",
  "They go through the gate and end up at the \n castle gallery.",
  "There are three doors in front of them.", 
  "Blam charges ahead and tries to open the big \n door labeled throne room.",
  "It is locked.",
  "Boq peeks through the left door.",
  "There are two small monsters behind this \n door.",
  "There’s a key at the end.",
  "Bart peeks through the right door.",
  "There’s one really big monster behind this \n one.",
  "There’s also a key at the end.",
  "Let’s really consider our options here.",
  "Do we want to go through the right, shorter \n and harder door or the left, longer and \n easier door?",
  "Let’s stay safe and take the easier route!",
  "Fight begins",
  "Thank god we beat that guy.",
  "I never like fighting food, it makes me \n hungry.",
  "Slow pan onto a hot dog shaped man.",
  "Fight begins",
  "Let’s do the harder one, we’re not scared!",
  "Fight begins",
  "YIPPEE!",
  "Gret grabs the key.",
  "I’m so glad that’s over.",
  "I wonder what the key leads to.",
  "Obviously it’s for the big door.",
  "Loser.",
  "Relax Blam.",
  "Let’s go back to the throne room door.",
  "They walk back to the gallery.",
  "Boq skips along.",
  "Are you guys ready to face the King?",
  "Boq whimpers in fear.",
  "Come on Boq, grow up we have to do this!",
  "Boq starts to cry.",
  "Blam! You made him cry!",
  "Apologize right now!",
  "Whatever.",
  "Blam takes the key from Gret and suddenly \n opens the throne room door.",
  "The doors swing open dramatically.",
  "The King slowly turns around in his large, \n swiveling desk throne.",
  "Well well well. I’ve been expecting you.",
  "We’re gonna kill you!",
  "You destroyed everything!",
  "Look at Boq!",
  "He’s crying because of you!",
  "Gret and Bart glare at Blam while comforting \n Boq.",
  "Gret gets up and walks forward.",
  "My name is Gret . You killed my father, \n prepare to die.",
  "Boq pulls out a knife that he just like had on \n him for some reason.",
  "Boq....",
  "You...",
  "Where’d you get that knife?",
  "Battle Begins",
  "We finally did it!",
  "Gret runs into Blams arms and they start \n passionately start making out.",
  "Eugh...",
  "Bart picks up Boq and starts spinning him \n around in a circle.",
  "They all live happily ever after.",
  "The end.",
  "You win!!!"
  


};
//who says all above dialogue
String[] nameOrder = {
  "Boq",
  "Blam",
  "Gret",
  "Bart",
  "Bart",
  "Boq",
  " ",
  "Bart",
  " ",
  " ",
  " ",
  " ",
  "Gret",
  "Blam",
  "Blam", 
  " ",
  " ",
  " ",
  " ",
  " ",
  "Boq",
  "Boq",
  " ",
  "Bart",
  "Bart",
  "Gret",
  "Gret",
  "Gret",
  " ",
  "Bart",
  "Bart",
  " ",
  " ",
  "Blam",
  " ",
  "Boq",
  " ",
  "Gret",
  "Bart",
  "Blam",
  "Blam",
  "Gret",
  "Gret",
  " ",
  " ",
  "Bart",
  " ",
  "Blam",
  " ",
  "Bart",
  "Gret",
  "Blam",
  " ",
  " ",
  " ",
  "King",
  "Blam",
  "Blam",
  "Blam",
  "Blam",
  " ",
  " ",
  "Gret",
  " ",
  "Bart",
  "Bart",
  "Bart",
  " ", 
  "Bart",
  " ",
  "Boq",
  " ",
  " ",
  " ",
  " "
};
public void setup() {
  //load images, resize and initialize characters
  /* size commented out by preprocessor */;
  castleImg = loadImage("castlebackground.jpg");
  battleBackground = loadImage("battleBackground.png");
  cheeseImg = loadImage("cheese.png");
  boqImg = loadImage("boq.png");
  blamImg = loadImage("blam.png");
  gretImg = loadImage("gret.png");
  bartImg = loadImage("bart.png");
  wolfImg = loadImage("wolf.png");
  ghostImg = loadImage("ghost.png");
  kingImg = loadImage("king.png");
  hotDogImg = loadImage("hotDog.png");
  gretImg.resize(100, 0);
  blamImg.resize(100, 0);
  bartImg.resize(100, 0);
  boqImg.resize(100, 0);
  hotDogImg.resize(100, 0);
  wolfImg.resize(100, 0);
  kingImg.resize(150, 0);
  Bart = new characters("Bart", 10, bartImg);
  Boq = new characters("Boq", 10, boqImg);
  Gret = new characters("Gret", 10, gretImg);
  Blam = new characters("Blam", 10, blamImg);
  Cheese = new characters("Cheese", 10, cheeseImg, 3);
  Ghost = new characters("Ghost", 20, ghostImg, 4);
  King = new characters("King", 10, kingImg, 5);
  Wolf = new characters("Wolf", 10, wolfImg, 3);
  HotDog = new characters("Hot Dog", 10, hotDogImg, 2);
  background(castleImg);
  font = loadFont("GoudyOldStyle.vlw");
  //start the dialogue
  dialogue.dDraw();
  //title
      fill(0);
    textSize(50);
    text("Castle Adventure", 70, 100);

}
public void draw() {
  //lose screen
  if(lose){
    background(0);
    text("You lose", 100, 100);
  }
  else{
    //clear title after first round
   if (round == 1){
    background(castleImg);
   }
   //clear screen intermitently 
  if(round == 27 || round == 35 || round == 29){
    background(castleImg);
  }
   //dialogue and battle scenes
  dialogue.dDraw();
  if (battleT){
   
    battle.bDraw();
  }
  //cycle through all dialogue depending on round number
  dialogue.setText(allDialogue[round], nameOrder[round]);
  //battle
  if(round == 9){
    battle.setEnemy(0);
    battleT = true;
  }
  //reset health after each battle
  if(!battleT){
   Bart.setHealth(10);
   Boq.setHealth(10);
   Gret.setHealth(10);
   Blam.setHealth(10);
   Cheese.setHealth(10);
   King.setHealth(10);
   Wolf.setHealth(10);
   Ghost.setHealth(20);
   HotDog.setHealth(10);
  }
  //choosing path
  if(round == 26){
    fill(181, 163, 139);
    rect(100, 250, 100, 200, 10);
    rect(250, 250, 100, 200, 10);
    fill(245, 220, 108);
    circle(180, 360, 20);
    circle(330, 360, 20);
  }
  //battles
  if(round == 28){
    battle.setEnemy(1);
    battleT = true;
  }
  if(round == 32){
    battle.setEnemy(2);
    battleT = true;
  }
  if(round == 34){
    round = 37;
    battle.setEnemy(3);
    battleT = true;
    
  }
  if(round == 67){
    battle.setEnemy(4);
    battleT = true;
  }
  //skip rounds that correspond with right door if user chose left door
  if(leftDoor && round == 33){
    round+=2;
  }
  }
}
//if mouse is over rectangle
public boolean overRect(int x, int y, int width, int height) {
  if (mouseX >= x && mouseX <= x+width && mouseY >= y && mouseY <= y+height) {
    return true;
  } else {
    return false;
  }
}
//if mouse is over circle
public boolean overCirc(int x, int y, int diameter) {
  float radius = diameter / 2.0f;
  float distX = mouseX - x;
  float distY = mouseY - y;
  return ((distX * distX + distY * distY) <= (radius * radius));
}
//logic for clicking on dilaogue buttons, door choices and battle choices
public void mousePressed() {
  if ((overRect(30, 580, 390, 100)) && !battleT && round != 26 && round != 33) {
    round++;
  }
  else if ((overRect(100, 250, 100, 200)) && !battleT && round == 26) {
    leftDoor = true;
    background(castleImg);
    round = 27;
  }
  else if ((overRect(250, 250, 100, 200)) && !battleT && round == 26) {
    leftDoor = false;
    background(castleImg);
    round = 33;
  }
  else if ((overRect(30, 580, 390, 100)) && !battleT && !leftDoor && round == 33) {
    round++;
  }
  else if ((overCirc(130, 400, 100))) {
    punch = true;
  }
  else if ((overCirc(330, 400, 100))) {
    kick = true;

  }
}
class battles{
  //initializing variables and lists
  int size;
  int turn = 0;
  int dead;
  int health;
  int enemy;
  ArrayList<characters> characterList = new ArrayList<>();
  ArrayList<PImage> characterImages = new ArrayList<>();
  ArrayList<characters> enemyList = new ArrayList<>();
  ArrayList<Integer> enemyHealth = new ArrayList<>();
  public void bDraw(){
    //fill in lists
    characterList.add(Gret);
    characterList.add(Blam);
    characterList.add(Bart);
    characterList.add(Boq);
    characterImages.add(gretImg);
    characterImages.add(blamImg);
    characterImages.add(bartImg);
    characterImages.add(boqImg);
    enemyList.add(Wolf);
    enemyList.add(Cheese);
    enemyList.add(HotDog);
    enemyList.add(Ghost);
    enemyList.add(King);
    enemyHealth.add(10);
    enemyHealth.add(10);
    enemyHealth.add(10);
    enemyHealth.add(20);
    enemyHealth.add(30);
    //set up battle screen
    background(battleBackground);
    image(enemyList.get(enemy).getImage(), 187, 220);
    fill(196, 196, 196);
    rect(140, 190, 200, 20, 50);
    fill(240, 108, 98);
    circle(130, 400, 100);
    fill(132, 158, 250);
    circle(330, 400, 100);
    fill(217, 37, 24);
    fill(0);
    textSize(27);
    text("Kick", 305, 407);
    text("Punch", 94, 408);
    //enemy health bar
    for (int i = 10; i >= 0; i--){
      if(enemyList.get(enemy).getHealth() == 0){
        fill(196, 196, 196);
        rect(140, 190, 200, 20, 50);
      }
      else if(enemyList.get(enemy).getHealth() == 10){
        fill(217, 37, 24);
        rect(140, 490, 200, 20, 50);
      }  
      else if((enemyList.get(enemy).getHealth() == i) && i != 0){
        size = 200 - (abs(i-10) * 20);
        fill(217, 37, 24);
        rect(140, 190, size, 20, 50);
      }
    }
    //enemy name
    fill(255);
    textSize(20);
    text(enemyList.get(enemy).getName(), 213, 207);    
    fill(196, 196, 196);
    rect(140, 490, 200, 20, 50);
    //character health bar
    for (int i = 10; i >= 0; i--){
      if(characterList.get(turn).getHealth() == 0){
        fill(196, 196, 196);
        rect(140, 490, 200, 20, 50);
      }
      else if(characterList.get(turn).getHealth() == 10){
        fill(217, 37, 24);
        rect(140, 490, 200, 20, 50);
      }      
      else if((characterList.get(turn).getHealth() == i) && i != 0){
        size = 200 - (abs(i-10) * 20);
        fill(217, 37, 24);
        rect(140, 490, size, 20, 50);
      }
    }

    //character name
    fill(255);
    textSize(20);
    text((characterList.get(turn)).getName(), 213, 507);
    //kick and punch options
    if(kick){
      characterList.get(turn).setHealth((characterList.get(turn)).getHealth() - enemyList.get(enemy).getPower());
      turn++;
      enemyList.get(enemy).setHealth(enemyList.get(enemy).getHealth() - 2);
      kick = false;
    }
    if(punch){
      characterList.get(turn).setHealth((characterList.get(turn)).getHealth() - enemyList.get(enemy).getPower());
      turn++;
      enemyList.get(enemy).setHealth(enemyList.get(enemy).getHealth() - 1);
      punch = false;
    }
    //end battle if enemy is killed, reset all health of characters, reset turn and increment round
    if(enemyList.get(enemy).getHealth() <= 0){
      System.out.println("Enemy health is zero. Ending battle.");
      Bart.setHealth(10);
   Boq.setHealth(10);
   Gret.setHealth(10);
   Blam.setHealth(10);
   Cheese.setHealth(10);
   King.setHealth(10);
   Wolf.setHealth(10);
   Ghost.setHealth(10);
   HotDog.setHealth(10);
      turn = 0;
      background(castleImg);
      battleT = false;
      round++;
    }
    //cycle through characters, if one is dead skip over it
    if((characterList.get(turn)).getHealth() > 0){
      image(characterImages.get(turn), 187, 520);
    }
    else
    {
      dead++;
      turn++;
    }
    //if all characters die, reset all health and show lose screen
    if(dead >= 4){
      Bart.setHealth(10);
   Boq.setHealth(10);
   Gret.setHealth(10);
   Blam.setHealth(10);
   Cheese.setHealth(10);
   King.setHealth(10);
   Wolf.setHealth(10);
   Ghost.setHealth(10);
   HotDog.setHealth(10);
     lose = true;
     battleT = false;
     background(castleImg);
    }
  }
  //enemy setter
  public void setEnemy(int e){
    enemy = e;
  }
}
class characters{
  //charateristics (didn't get to implementing all of them, i was too ambitious)
  String name;
  int health;
  int healthInit;
  int power;
  int healthPower;
  int magicPower;
  PImage image;
  //character constructor
  public characters(String n, int h, PImage i, int p){
    name = n;
    health = h;
    image = i;
    power = p;
    healthInit = h;
  }
  //simple character constructor
  public characters(String n, int h, PImage i){
    name = n;
    health = h;
    image = i;
  }
  //getters and setters for health, name, image, power, and initial health
  public int getHealth(){  
    return health;
  }
   public int getHealthInit(){  
    return healthInit;
  }
  public void setHealth(int h){
    health = h;
  }
  public String getName(){  
    return name;
  }
  public PImage getImage(){
    return image;
  }
  public int getPower(){
    return power;
  }
}
  
class dialogueBubble{
  public String text;
  public String name = null;
  //dialogue constructors, what is in the text bubble
  public dialogueBubble(String t, String n){
    text = t;
    name = n;
  }
  public dialogueBubble(String t){
    text = t;
  }
  //draws the dialogue bubble
  public void dDraw(){
    fill(255);
    rect(30, 580, 390, 100, 30);
      rect(25, 550, 100, 50, 30);
      textFont(font, 36);
    fill(0);
    text(name, 39, 585);
    textFont(font, 20);
    text(text, 45, 630);
    fill(196, 196, 196);
    textFont(font, 15);
    text("Click to continue.", 175, 673);
  }
  //text setter
  public void setText(String t, String n){
    text = t;
    name = n;
  }
 
}
  


  public void settings() { size(451, 707); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "storybookGame" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
